export default {
            content: ["./*.html", "./*.js"],
            darkMode: "class",
            theme: {
                extend: {
                    "colors": {
                        "surface": "#f9faf4",
                        "primary": "#0b1829",
                        "surface-tint": "#525f72",
                        "surface-dim": "#d9dbd5",
                        "primary-container": "#202d3e",
                        "tertiary-fixed-dim": "#e2c28e",
                        "error-container": "#ffdad6",
                        "on-secondary": "#ffffff",
                        "tertiary": "#221500",
                        "secondary-container": "#d2e4fa",
                        "error": "#ba1a1a",
                        "on-primary-fixed": "#0f1c2d",
                        "on-error-container": "#93000a",
                        "on-primary-fixed-variant": "#3b485a",
                        "on-surface": "#1a1c19",
                        "blueprint-blue": "#2B3A4F",
                        "on-primary-container": "#8794a9",
                        "tertiary-fixed": "#ffdea9",
                        "on-tertiary-container": "#ac905f",
                        "inverse-on-surface": "#f0f1eb",
                        "on-tertiary-fixed-variant": "#59431a",
                        "inverse-primary": "#bac7dd",
                        "outline-variant": "#c5c6cd",
                        "outline": "#75777d",
                        "surface-container": "#edeee8",
                        "inverse-surface": "#2f312d",
                        "slate-border": "#D1D5DB",
                        "background": "#f9faf4",
                        "on-error": "#ffffff",
                        "secondary-fixed-dim": "#b7c8dd",
                        "machined-silver": "#E2E8F0",
                        "secondary": "#4f6072",
                        "surface-container-highest": "#e2e3dd",
                        "on-background": "#1a1c19",
                        "on-secondary-fixed": "#0b1d2c",
                        "tertiary-container": "#3c2903",
                        "surface-container-high": "#e8e9e3",
                        "on-secondary-fixed-variant": "#37485a",
                        "on-primary": "#ffffff",
                        "primary-fixed-dim": "#bac7dd",
                        "surface-container-lowest": "#ffffff",
                        "primary-fixed": "#d6e3fa",
                        "secondary-fixed": "#d2e4fa",
                        "on-tertiary": "#ffffff",
                        "on-tertiary-fixed": "#271900",
                        "surface-container-low": "#f3f4ee",
                        "on-secondary-container": "#556678",
                        "surface-variant": "#e2e3dd",
                        "on-surface-variant": "#44474c",
                        "surface-bright": "#f9faf4"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.125rem",
                        "lg": "0.25rem",
                        "xl": "0.5rem",
                        "full": "0.75rem"
                    },
                    "spacing": {
                        "margin-mobile": "20px",
                        "stack-md": "16px",
                        "container-max": "1280px",
                        "stack-lg": "32px",
                        "margin-desktop": "64px",
                        "stack-xs": "4px",
                        "gutter": "24px",
                        "unit": "8px"
                    },
                    "fontFamily": {
                        "display-lg": ["Montserrat"],
                        "headline-md": ["Montserrat"],
                        "headline-sm": ["Montserrat"],
                        "body-md": ["Inter"],
                        "button": ["Montserrat"],
                        "label-caps": ["JetBrains Mono"],
                        "body-lg": ["Inter"],
                        "body-sm": ["Inter"]
                    },
                    "fontSize": {
                        "display-lg": ["4rem", { lineHeight: "1.1", letterSpacing: "-0.02em" }],
                        "headline-md": ["2.25rem", { lineHeight: "2.5rem" }],
                        "headline-sm": ["1.5rem", { lineHeight: "2rem" }],
                        "body-lg": ["1.125rem", { lineHeight: "1.75rem" }],
                        "body-md": ["1rem", { lineHeight: "1.5rem" }],
                        "body-sm": ["0.875rem", { lineHeight: "1.25rem" }],
                        "button": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.05em" }],
                        "label-caps": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.1em" }]
                    }
                }
            }
        }